### ISSUE TITLE
Merge the branch serial

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/blink-platformio#1]
Try the branch serial and try to refactor the code so that it works.

The goal is to have a menu from the serial monitor.

You may try to get a spectrophotometer in order to play with it and try the code.

We may discuss about some more refactoring of the code but the current idea is to move slowly more and more code from the bioreactor-platformio project to this project (step by step will be easier to debug and improve probably).

**Comment by andrescvargasr** [comment]
**Update**: Monitoring and Serial threads work

1. Change **lib/hack/SerialUtilities.cpp**:
2. Change **lib/hack/eeprom.cpp**:
3. Install **Time.h** library.
4. Change **lib/hack/params.h**:
5. Create: Monitoring.h, Serial.h, and StartThreads.h.
6. Modify: Monitoring.cpp, and StartThreads.h.
7. Create Serial.cpp into src folder.

Pending:

1. Refactor hack folder.
2. Check params.h, hex.h, and SerialUtilities.h files.

Test:

- Upload code and type 'h' into Serial Terminal.

Testing board:

- StandardTransducer V2.0 (Lilypad USB compatible board).

**Comment by andrescvargasr** [comment]
# **Update**: params, SerialMonitoring, eeprom, toHex (.h and .cpp files) work.

- Change **/hack/params.h** to /include/params.h and src/params.cpp.
- Change **/hack/SerialUtilties** files to /include/SerialUtilities.h and src/SerialUtilities.cpp.
- Change **/hack/toHex** files to /include/toHex.h and src/toHex.cpp.
- Change **/hack/eeprom** files to /include/eeprom.h and src/eeprom.cpp.

# Pending:

- Refactor SerialMonitoring, eeprom, and toHex files.

Test:

- All commands work: Type: _h_, _s_, and _u_ into Serial Terminal.

Testing board:

    StandardTransducer V2.0 (Lilypad USB compatible board).
